name: Publish Package

on:
  push:
    branches: [ "master" ]
    
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ncipollo/release-action@v1
      with:
        #artifacts: "target/excavator.jar"
        #replacesArtifacts: true
        tag: "PgGeocoder-run${{ github.run_number }}"
        name: "PgGeocoder"
        makeLatest: true        
        allowUpdates: false
        token: ${{ secrets.GITHUB_TOKEN }}
